### ISSUE TITLE
Что сделал не так и как исправить

### ISSUE THREAD

**Issue by Cthujrjpkjd2147782** [SunOner/yolov8_aimbot#117]
C:\Users\ПК\Desktop\yolov8_aimbot-main>py run.py
PT Model loaded.
Aimbot is started. Enjoy!
[Right mouse button] - Aiming at the target
[F2] - EXIT
C:\Users\ПК\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\cuda\__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ..\c10\cuda\CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Ultralytics YOLOv8.0.227 🚀 Python-3.11.6 torch-2.1.1+cu121
Traceback (most recent call last):
  File "C:\Users\ПК\Desktop\yolov8_aimbot-main\run.py", line 169, in <module>
    init()
  File "C:\Users\ПК\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ПК\Desktop\yolov8_aimbot-main\run.py", line 108, in init
    result = model.predict(
             ^^^^^^^^^^^^^^
  File "C:\Users\ПК\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 232, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "C:\Users\ПК\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 318, in setup_model
    device=select_device(self.args.device, verbose=verbose),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ПК\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\torch_utils.py", line 119, in select_device
    raise ValueError(f"Invalid CUDA 'device={device}' requested."
ValueError: Invalid CUDA 'device=0' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: None
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.

**Comment by vuchaev2015** [comment]
Установи PyTorch с официального сайта, CUDA твоей версии. https://pytorch.org/
