### ISSUE TITLE
AttributeError: 'DXCamera' object has no attribute 'is_capturing'

### ISSUE THREAD

**Issue by 0hEve** [SunOner/yolov8_aimbot#154]
File "C:\Users\kevin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dxcam\__init__.py", line 71, in create
    camera = DXCamera(
  File "C:\Users\kevin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dxcam\dxcam.py", line 33, in __init__
    self._duplicator: Duplicator = Duplicator(
  File "<string>", line 6, in __init__
  File "C:\Users\kevin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dxcam\core\duplicator.py", line 19, in __post_init__
    output.output.DuplicateOutput(device.device, ctypes.byref(self.duplicator))
_ctypes.COMError: (-2005270524, 'The specified device interface or feature level is not supported on this system.', (None, None, None, 0, None))
Exception ignored in: <function DXCamera.__del__ at 0x000001CD0BE467A0>
Traceback (most recent call last):
  File "C:\Users\kevin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dxcam\dxcam.py", line 243, in __del__
    self.release()
  File "C:\Users\kevin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dxcam\dxcam.py", line 238, in release
    self.stop()
  File "C:\Users\kevin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dxcam\dxcam.py", line 138, in stop
    if self.is_capturing:
AttributeError: 'DXCamera' object has no attribute 'is_capturing'

I selected the correct gpu, and it still doesnt work, whatever i have read in the issue section till now, did not help.
![image](https://github.com/SunOner/yolov8_aimbot/assets/132481051/693bd2f0-7b40-4525-9d8f-896ad2c640e6)

**Comment by Weser87** [comment]
you are trying python 3.10 from microsoft story.

**Comment by SunOner** [comment]
Yes, don't use the python version from the Microsoft store. Download it from the official website.
