### ISSUE TITLE
Crash Instantly

### ISSUE THREAD

**Issue by Nico53425342** [SunOner/yolov8_aimbot#156]
This is the error, it happens each time one of my game are open, I try many times to bypass it by minimizing the windows then opening up after, but it don't stop crashing.
I love your project and how organize is the repositories, thank you guys for this gold. :)

Traceback (most recent call last):
  File "C:\Users\nicol\AppData\Local\Programs\Python\Python311\Lib\site-packages\bettercam\bettercam.py", line 184, in __capture
    self.__frame_buffer[self.__head] = frame
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
ValueError: could not broadcast input array from shape (216,384,3) into shape (1080,1920,3)

Exception in thread BetterCam:
Traceback (most recent call last):
  File "C:\Users\nicol\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\nicol\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\nicol\AppData\Local\Programs\Python\Python311\Lib\site-packages\bettercam\bettercam.py", line 213, in __capture
    self.stop()
  File "C:\Users\nicol\AppData\Local\Programs\Python\Python311\Lib\site-packages\bettercam\bettercam.py", line 147, in stop
    self.__thread.join(timeout=10)
  File "C:\Users\nicol\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1116, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

**Comment by Nico53425342** [comment]
i did more testing and the crash happen only when a software (.exe) window pass though the center of the capturing.

**Comment by SunOner** [comment]
ValueError: could not broadcast input array from shape (216,384,3) into shape (1080,1920,3)
This happens then game changing screen resolution, try set window mode in game.

**Comment by SunOner** [comment]
Whatever the window does not close, run run.py from the console, and so I think that the error is related to torch and ultralytics, reinstall these packages.

**Comment by Nico53425342** [comment]
i'm not that good with commands and python stuff. Can you tell me what command do i need to write for reinstall torch and ultralytics, thx.

**Comment by SunOner** [comment]
`pip uninstall torch torchvision torchaudio ultralytics`
`pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121`
`pip install ultralytics`

**Comment by Nico53425342** [comment]
thx man appreciate it :) 💯

**Comment by Sdka2345123** [comment]
Что делать я прописал эти команды и после этого запустил "run" и в этом командном строке ничего не происходит с чем это может быть связано?
