### ISSUE TITLE
ModuleNotFoundError: No module named 'bettercam'

### ISSUE THREAD

**Issue by djizi** [SunOner/yolov8_aimbot#161]
C:\Users\xKiza\OneDrive\Рабочий стол\sosipetuxi>py run.py
Traceback (most recent call last):
  File "C:\Users\xKiza\OneDrive\Рабочий стол\sosipetuxi\run.py", line 14, in <module>
    from logic.capture import *
  File "C:\Users\xKiza\OneDrive\Рабочий стол\sosipetuxi\logic\capture.py", line 2, in <module>
    import bettercam
ModuleNotFoundError: No module named 'bettercam'

**Comment by SunOner** [comment]
`pip install bettercam`
