### ISSUE TITLE
ValueError: Invalid CUDA 'device=0' requested

### ISSUE THREAD

**Issue by Gleb-desygn** [SunOner/yolov8_aimbot#164]
ValueError: Invalid CUDA 'device=0' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: None
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.

how to fix and how to launch this artificial intelligence????

**Comment by Gleb-desygn** [comment]
TTraceback (most recent call last):
  File "C:\Users\Professional\Desktop\yolov8_aimbot-main\run.py", line 198, in <module>
    init()
  File "C:\Users\Professional\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Professional\Desktop\yolov8_aimbot-main\run.py", line 86, in init
    result = model.predict(
             ^^^^^^^^^^^^^^
  File "C:\Users\Professional\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 250, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "C:\Users\Professional\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 321, in setup_model
    device=select_device(self.args.device, verbose=verbose),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Professional\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\torch_utils.py", line 119, in select_device
    raise ValueError(f"Invalid CUDA 'device={device}' requested."
ValueError: Invalid CUDA 'device=0' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: None
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.

**Comment by Gleb-desygn** [comment]
ValueError: Invalid CUDA 'device=0' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: None
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.

how to fix and how to launch this artificial intelligence????

**Comment by Gleb-desygn** [comment]
how to fix and how to launch this artificial intelligence????

**Comment by SunOner** [comment]
Please re-install torch with GPU support.
