### ISSUE TITLE
При развороте полноэкранного режима варфейс, выскакивает эта ошибка.

### ISSUE THREAD

**Issue by Utrenia** [SunOner/yolov8_aimbot#166]
Aimbot is started. Enjoy!
[RightMouseButton] - Aiming at the target
[F6] - EXIT
[F3] - PAUSE AIM
[F4] - Reload config
Loading models\sunxds_0.3.7.engine for TensorRT inference...
[01/04/2024-04:45:17] [TRT] [I] Loaded engine size: 61 MiB
[01/04/2024-04:45:17] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +60, now: CPU 0, GPU 60 (MiB)
[01/04/2024-04:45:17] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +9, now: CPU 0, GPU 69 (MiB)
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\bettercam\bettercam.py", line 184, in __capture
    self.__frame_buffer[self.__head] = frame
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
ValueError: could not broadcast input array from shape (216,384,3) into shape (1080,1920,3)

Exception in thread BetterCam:
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python311\Lib\site-packages\bettercam\bettercam.py", line 213, in __capture
    self.stop()
  File "C:\Program Files\Python311\Lib\site-packages\bettercam\bettercam.py", line 147, in stop
    self.__thread.join(timeout=10)
  File "C:\Program Files\Python311\Lib\threading.py", line 1116, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

**Comment by SunOner** [comment]
[9 пункт](https://github.com/SunOner/yolov8_aimbot/blob/main/docs/ru/questions_ru.md)
