### ISSUE TITLE
NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend.

### ISSUE THREAD

**Issue by foecerip23** [SunOner/yolov8_aimbot#187]
Просто запускается пишет вот это в игру заходишь не чего не работает. и вылазит такой текст: 
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\yolov8_aimbot-main\run.py", line 214, in <module>
    init()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\yolov8_aimbot-main\run.py", line 127, in init
    for frame in result:
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 290, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\models\yolo\detect\predict.py", line 25, in postprocess
    preds = ops.non_max_suppression(
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\ops.py", line 278, in non_max_suppression
    i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\ops\boxes.py", line 41, in nms
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\_ops.py", line 692, in call
    return self._op(*args, **kwargs or {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends: [CPU, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].
![Снимок](https://github.com/SunOner/yolov8_aimbot/assets/156350396/fbc7fa69-f918-4711-8a2d-cb085b1f0651)

**Comment by SunOner** [comment]
https://github.com/SunOner/yolov8_aimbot/issues/185
https://github.com/SunOner/yolov8_aimbot/issues/184
https://github.com/SunOner/yolov8_aimbot/issues/112
https://github.com/SunOner/yolov8_aimbot/issues/71
https://github.com/SunOner/yolov8_aimbot/issues/67
https://github.com/SunOner/yolov8_aimbot/issues/36
https://github.com/SunOner/yolov8_aimbot/issues/35
https://github.com/SunOner/yolov8_aimbot/issues/32

**Comment by foecerip23** [comment]
И так же долго наводится на цели можно ли как-то исправить это, и есть ли возможность убрать наведение на своих?
