### ISSUE TITLE
 Hi how do I make this work?

### ISSUE THREAD

**Issue by Allmight0000** [SunOner/yolov8_aimbot#2]
I use a fullhd 1920x1080 monitor, just change this in the options? Another thing, how do I export the pt model to tensor? Do you have any video tutorials on how to make the script work? I have some models in yolov5 if I can get this script to work I can train models and provide them to you in advance, thanks in advance

**Comment by SunOner** [comment]
Hi, at the expense of the screen resolution, yes, there are 1920, 1080 in the options file. To export a model from the *.pt format to the .engine format, run the command "yolo export model="path to the model" format=engine". A video of how the script works will be a little later. The yolov5 format is not supported in this version, you can train a new model using the coco 8.yaml config file that I provided in the repository.

**Comment by Allmight0000** [comment]
WARNING  Unable to automatically guess model task, assuming 'task=detect'. Explicitly define task for your model, i.e. 'task=detect', 'segment', 'classify', or 'pose'.
Loading models\all_1.engine for TensorRT inference...
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\idlelib\run.py", line 578, in runcode
    exec(code, self.locals)
  File "C:\Users\Administrator\Downloads\yolov8_aimbot-main\yolov8_aimbot-main\main.py", line 212, in <module>
    init()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\yolov8_aimbot-main\yolov8_aimbot-main\main.py", line 69, in init
    result = model(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\model.py", line 96, in __call__
    return self.predict(source, stream, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\model.py", line 229, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\predictor.py", line 305, in setup_model
    self.model = AutoBackend(model or self.args.model,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\nn\autobackend.py", line 175, in __init__
    context = model.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
