### ISSUE TITLE
помогите пж

### ISSUE THREAD

**Issue by AntiAzer** [SunOner/yolov8_aimbot#204]
C:\Users\Rusik\Desktop\yolov8_aimbot-main>py run.py
PT Model loaded.
Aimbot is started. Enjoy!
[RightMouseButton] - Aiming at the target
[F2] - EXIT
[F3] - PAUSE AIM
Traceback (most recent call last):
  File "C:\Users\Rusik\Desktop\yolov8_aimbot-main\run.py", line 205, in <module>
    init()
  File "C:\Users\Rusik\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rusik\Desktop\yolov8_aimbot-main\run.py", line 120, in init
    frame = get_new_frame()
            ^^^^^^^^^^^^^^^
  File "C:\Users\Rusik\Desktop\yolov8_aimbot-main\logic\frame.py", line 26, in get_new_frame
    dx = dxcam.create(device_idx=dxcam_monitor_id, output_idx=dxcam_gpu_id, output_color="BGR", max_buffer_len=dxcam_max_buffer_len)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rusik\AppData\Local\Programs\Python\Python311\Lib\site-packages\dxcam\__init__.py", line 112, in create
    return __factory.create(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Rusik\AppData\Local\Programs\Python\Python311\Lib\site-packages\dxcam\__init__.py", line 71, in create
    camera = DXCamera(
             ^^^^^^^^^
  File "C:\Users\Rusik\AppData\Local\Programs\Python\Python311\Lib\site-packages\dxcam\dxcam.py", line 33, in __init__
    self._duplicator: Duplicator = Duplicator(
                                   ^^^^^^^^^^^
  File "<string>", line 6, in __init__
  File "C:\Users\Rusik\AppData\Local\Programs\Python\Python311\Lib\site-packages\dxcam\core\duplicator.py", line 19, in __post_init__
    output.output.DuplicateOutput(device.device, ctypes.byref(self.duplicator))
_ctypes.COMError: (-2005270524, 'Указанный интерфейс устройства или уровень компонента не поддерживается в данной системе.', (None, None, None, 0, None))
Exception ignored in: <function DXCamera.__del__ at 0x0000018C4B597D80>
Traceback (most recent call last):
  File "C:\Users\Rusik\AppData\Local\Programs\Python\Python311\Lib\site-packages\dxcam\dxcam.py", line 243, in __del__
    self.release()
  File "C:\Users\Rusik\AppData\Local\Programs\Python\Python311\Lib\site-packages\dxcam\dxcam.py", line 238, in release
    self.stop()
  File "C:\Users\Rusik\AppData\Local\Programs\Python\Python311\Lib\site-packages\dxcam\dxcam.py", line 138, in stop
    if self.is_capturing:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'DXCamera' object has no attribute 'is_capturing'

**Comment by SunOner** [comment]
[Смотри 16 пункт](https://github.com/SunOner/yolov8_aimbot/blob/main/docs/ru/questions_ru.md)

**Comment by SunOner** [comment]
Обнови программу

**Comment by AntiAzer** [comment]
а где взять новую программу?? я скачал ей с телеграм чата

**Comment by AntiAzer** [comment]
я исправил ошибку поставил оконный режим без рамок и ошибка убралась но AI не наводит на голову
