### ISSUE TITLE
Error main.py 

### ISSUE THREAD

**Issue by wanwa0412** [SunOner/yolov8_aimbot#32]
Model loaded. None
Traceback (most recent call last):
  File "D:\23321\yolov8_aimbot-main\yolov8_aimbot-main\main.py", line 145, in <module>
    init()
  File "C:\Users\valor\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\23321\yolov8_aimbot-main\yolov8_aimbot-main\main.py", line 113, in init
    for frame in result:
  File "C:\Users\valor\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "C:\Users\valor\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 269, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\valor\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\models\yolo\detect\predict.py", line 25, in postprocess
    preds = ops.non_max_suppression(preds,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\valor\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\ops.py", line 238, in non_max_suppression
    i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\valor\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\ops\boxes.py", line 41, in nms
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\valor\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends: [CPU, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

CPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\cpu\nms_kernel.cpp:112 [kernel]
QuantizedCPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\quantized\cpu\qnms_kernel.cpp:124 [kernel]
BackendSelect: fallthrough registered at ..\aten\src\ATen\core\BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:153 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:498 [backend fallback]
Functionalize: registered at ..\aten\src\ATen\FunctionalizeFallbackKernel.cpp:290 [backend fallback]
Named: registered at ..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at ..\aten\src\ATen\ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at ..\aten\src\ATen\native\NegateFallback.cpp:19 [backend fallback]
ZeroTensor: registered at ..\aten\src\ATen\ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:86 [backend fallback]
AutogradOther: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:53 [backend fallback]
AutogradCPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:57 [backend fallback]
AutogradCUDA: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:65 [backend fallback]
AutogradXLA: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:69 [backend fallback]
AutogradMPS: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:77 [backend fallback]
AutogradXPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:61 [backend fallback]
AutogradHPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:90 [backend fallback]
AutogradLazy: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:73 [backend fallback]
AutogradMeta: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:81 [backend fallback]
Tracer: registered at ..\torch\csrc\autograd\TraceTypeManual.cpp:296 [backend fallback]
AutocastCPU: fallthrough registered at ..\aten\src\ATen\autocast_mode.cpp:382 [backend fallback]
AutocastCUDA: fallthrough registered at ..\aten\src\ATen\autocast_mode.cpp:249 [backend fallback]
FuncTorchBatched: registered at ..\aten\src\ATen\functorch\LegacyBatchingRegistrations.cpp:710 [backend fallback]
FuncTorchVmapMode: fallthrough registered at ..\aten\src\ATen\functorch\VmapModeRegistrations.cpp:28 [backend fallback]
Batched: registered at ..\aten\src\ATen\LegacyBatchingRegistrations.cpp:1075 [backend fallback]
VmapMode: fallthrough registered at ..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at ..\aten\src\ATen\functorch\TensorWrapper.cpp:203 [backend fallback]
PythonTLSSnapshot: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:161 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:494 [backend fallback]
PreDispatch: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:165 [backend fallback]
PythonDispatcher: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:157 [backend fallback]

**Comment by wanwa0412** [comment]
pip install ultralytics

**Comment by wanwa0412** [comment]
pip install ultralytics

**Comment by wanwa0412** [comment]
My options file:

# Desktop screen resolution
original_screen_width = 1920
original_screen_height = 1080

# Object Search window resolution
screen_width = 380
screen_height = 380

# Dxcam Capture method
Dxcam_capture = True
dxcam_capture_fps = 35 # 30 fps is OK
dxcam_monitor_id = 0
dxcam_gpu_id = 0
dxcam_max_buffer_len = 64

# Obs capture method
Obs_capture = False
Obs_camera_id = 1
Obs_capture_fps = 30 # 30 fps is OK

# Windows capture method
native_Windows_capture = False

# Aim settings
body_y_offset = -0.20
hideout_targets = False

# Mouse settings 
mouse_smoothing = 2 # 1 is default
mouse_auto_shoot = False
mouse_auto_aim = False
mouse_native = False
mouse_wild_mouse = False

# AI options
AI_model_path = 'models/sunxds_0.2.1_640.pt' # You can find new improved models here https://boosty.to/sunone
AI_image_size = 640
AI_conf = 0.35
AI_iou = 0.1
AI_device = 0
AI_max_det = 10

# Cv2 debug window settings
show_window = True
show_speed = True
show_fps = True
show_boxes = True
show_labels = True
show_conf = True
debug_window_scale_percent = 100
debug_window_name = 'Calculator'

**Comment by wanwa0412** [comment]
checks.py 
Ultralytics YOLOv8.0.221 🚀 Python-3.11.6 torch-2.1.1+cu121 CUDA:0 (NVIDIA GeForce GTX 1060 6GB, 6144MiB)
Setup complete ✅ (12 CPUs, 15.9 GB RAM, 529.7/949.2 GB disk)

OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.11.6
Install             pip
RAM                 15.92 GB
CPU                 Intel Core(TM) i7-8700 3.20GHz
CUDA                12.1

matplotlib          ✅ 3.8.2>=3.3.0
numpy               ✅ 1.24.1>=1.22.2
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 9.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.28.1>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
torch               ✅ 2.1.1+cu121>=1.8.0
torchvision         ✅ 0.16.1>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 2.1.3>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

Cuda support True
OpenCV version: 4.8.1
Model summary: 225 layers, 11139470 parameters, 0 gradients, 28.7 GFLOPs
(225, 11139470, 0, 28.666316800000004)
numpy version: 1.24.1
DXcam devices info:
Device[0] Output[0]: Res:(1920, 1080) Rot:0 Primary:True

asyncio version: 3.4.3
Options file checks:

original_screen_width 1920
original_screen_height 1080

screen_width 380
screen_height 380

Dxcam_capture True
dxcam_capture_fps 35
dxcam_monitor_id 0
dxcam_gpu_id 0
dxcam_max_buffer_len 64

Obs_capture False
Obs_camera_id 1
Obs_capture_fps 30

native_Windows_capture False

body_y_offset -0.2
hideout_targets False

mouse_smoothing 2
mouse_auto_shoot False
mouse_auto_aim False
mouse_native False

AI_model_path models/sunxds_0.2.1_640.pt
AI_image_size 640
AI_conf 0.35
AI_iou 0.1
AI_device 0
AI_max_det 10
show_window True
show_speed True
show_fps True
show_boxes True
show_labels True
show_conf True
debug_window_scale_percent 100
debug_window_name Calculator

Environment variables:

ALLUSERSPROFILE: C:\ProgramData
APPDATA: C:\Users\valor\AppData\Roaming
CHOCOLATEYINSTALL: C:\ProgramData\chocolatey
CHOCOLATEYLASTPATHUPDATE: 133380056689301685
COMMONPROGRAMFILES: C:\Program Files\Common Files
COMMONPROGRAMFILES(X86): C:\Program Files (x86)\Common Files
COMMONPROGRAMW6432: C:\Program Files\Common Files
COMPUTERNAME: DESKTOP-7BII2KG
COMSPEC: C:\WINDOWS\system32\cmd.exe
CUDA_INJECTION64_PATH: C:\Program Files (x86)\NVIDIA Corporation\Nsight Visual Studio Edition 2023.3\Monitor\Common\Injection64\Nvda.Cuda.Injection.dll
CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1
CUDA_PATH_V12_1: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1
CUDA_PATH_V12_3: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3
DRIVERDATA: C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING: Default
HOMEDRIVE: C:
HOMEPATH: \Users\valor
LOCALAPPDATA: C:\Users\valor\AppData\Local
LOGONSERVER: \\DESKTOP-7BII2KG
NUMBER_OF_PROCESSORS: 12
ONEDRIVE: C:\Users\valor\OneDrive
ONEDRIVECONSUMER: C:\Users\valor\OneDrive
OS: Windows_NT
PATH: C:\Users\valor\AppData\Local\Programs\Python\Python311\Lib\site-packages\cv2\../../x64/vc14/bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\libnvvp;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\libnvvp;;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Process Lasso\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\dotnet\;C:\Program Files\NVIDIA Corporation\Nsight Compute 2023.1.0\;C:\Users\valor\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\valor\AppData\Local\Programs\Python\Python311\;C:\Users\valor\AppData\Local\Programs\Python\Python312\Scripts\;C:\Users\valor\AppData\Local\Programs\Python\Python312\;C:\Users\valor\AppData\Local\Microsoft\WindowsApps;C:\Users\valor\AppData\Roaming\npm;C:\Users\valor\.dotnet\tools;C:\Program Files\JetBrains\PyCharm 2023.2.5\bin;;D:\23321\yolov8_aimbot-main\yolov8_aimbot-main\TensorRT-8.6.1.6\lib;
PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE: AMD64
PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
PROCESSOR_LEVEL: 6
PROCESSOR_REVISION: 9e0a
PROGRAMDATA: C:\ProgramData
PROGRAMFILES: C:\Program Files
PROGRAMFILES(X86): C:\Program Files (x86)
PROGRAMW6432: C:\Program Files
PROMPT: $P$G
PSMODULEPATH: C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC: C:\Users\Public
PYCHARM: C:\Program Files\JetBrains\PyCharm 2023.2.5\bin;
SESSIONNAME: Console
SYSTEMDRIVE: C:
SYSTEMROOT: C:\WINDOWS
TEMP: C:\Users\valor\AppData\Local\Temp
TMP: C:\Users\valor\AppData\Local\Temp
USERDOMAIN: DESKTOP-7BII2KG
USERDOMAIN_ROAMINGPROFILE: DESKTOP-7BII2KG
USERNAME: valor
USERPROFILE: C:\Users\valor
WINDIR: C:\WINDOWS
NUMEXPR_MAX_THREADS: 8
CUBLAS_WORKSPACE_CONFIG: :4096:8
TF_CPP_MIN_LOG_LEVEL: 2
CUDA_MODULE_LOADING: LAZY

D:\23321\yolov8_aimbot-main\yolov8_aimbot-main>python main.py
Model loaded. None
Traceback (most recent call last):
  File "D:\23321\yolov8_aimbot-main\yolov8_aimbot-main\main.py", line 145, in <module>
    init()
  File "C:\Users\valor\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\23321\yolov8_aimbot-main\yolov8_aimbot-main\main.py", line 113, in init
    for frame in result:
  File "C:\Users\valor\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "C:\Users\valor\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 269, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\valor\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\models\yolo\detect\predict.py", line 25, in postprocess
    preds = ops.non_max_suppression(preds,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\valor\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\ops.py", line 238, in non_max_suppression
    i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\valor\AppData\Local\Programs\Python\Python311\Lib\site-packages\torchvision\ops\boxes.py", line 41, in nms
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\valor\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends: [CPU, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

CPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\cpu\nms_kernel.cpp:112 [kernel]
QuantizedCPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\quantized\cpu\qnms_kernel.cpp:124 [kernel]
BackendSelect: fallthrough registered at ..\aten\src\ATen\core\BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:153 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:498 [backend fallback]
Functionalize: registered at ..\aten\src\ATen\FunctionalizeFallbackKernel.cpp:290 [backend fallback]
Named: registered at ..\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at ..\aten\src\ATen\ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at ..\aten\src\ATen\native\NegateFallback.cpp:19 [backend fallback]
ZeroTensor: registered at ..\aten\src\ATen\ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:86 [backend fallback]
AutogradOther: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:53 [backend fallback]
AutogradCPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:57 [backend fallback]
AutogradCUDA: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:65 [backend fallback]
AutogradXLA: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:69 [backend fallback]
AutogradMPS: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:77 [backend fallback]
AutogradXPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:61 [backend fallback]
AutogradHPU: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:90 [backend fallback]
AutogradLazy: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:73 [backend fallback]
AutogradMeta: registered at ..\aten\src\ATen\core\VariableFallbackKernel.cpp:81 [backend fallback]
Tracer: registered at ..\torch\csrc\autograd\TraceTypeManual.cpp:296 [backend fallback]
AutocastCPU: fallthrough registered at ..\aten\src\ATen\autocast_mode.cpp:382 [backend fallback]
AutocastCUDA: fallthrough registered at ..\aten\src\ATen\autocast_mode.cpp:249 [backend fallback]
FuncTorchBatched: registered at ..\aten\src\ATen\functorch\LegacyBatchingRegistrations.cpp:710 [backend fallback]
FuncTorchVmapMode: fallthrough registered at ..\aten\src\ATen\functorch\VmapModeRegistrations.cpp:28 [backend fallback]
Batched: registered at ..\aten\src\ATen\LegacyBatchingRegistrations.cpp:1075 [backend fallback]
VmapMode: fallthrough registered at ..\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at ..\aten\src\ATen\functorch\TensorWrapper.cpp:203 [backend fallback]
PythonTLSSnapshot: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:161 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at ..\aten\src\ATen\functorch\DynamicLayer.cpp:494 [backend fallback]
PreDispatch: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:165 [backend fallback]
PythonDispatcher: registered at ..\aten\src\ATen\core\PythonFallbackKernel.cpp:157 [backend fallback]

**Comment by Mooozzzuj** [comment]
@SunOner C:\yolov8_aimbot-main>pip uninstall torch torchvision torchaudio
WARNING: Skipping torch as it is not installed.
WARNING: Skipping torchvision as it is not installed.
WARNING: Skipping torchaudio as it is not installed.

**Comment by Mooozzzuj** [comment]
@SunOner C:\yolov8_aimbot-main>pip install torchvision torchaudio -index-url https://download.pytorch.org/whl/cu121
WARNING: The index url "ndex-url" seems invalid, please provide a scheme.
Looking in indexes: ndex-url
Collecting https://download.pytorch.org/whl/cu121
  Downloading https://download.pytorch.org/whl/cu121 (1.7 kB)
  ERROR: Cannot unpack file C:\Users\2222\AppData\Local\Temp\pip-unpack-jz1_5vw1\cu121.html (downloaded from C:\Users\2222\AppData\Local\Temp\pip-req-build-_8l37_ci, content-type: text/html); cannot detect archive format
ERROR: Cannot determine archive format of C:\Users\2222\AppData\Local\Temp\pip-req-build-_8l37_ci

**Comment by SunOner** [comment]
'pip uninstall torch torchvision torchaudio'
'pip install torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121'

**Comment by wanwa0412** [comment]
> 'pip uninstall torch torchvision torchaudio' 'pip install torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121'

it's working. thanks for support <3
