### ISSUE TITLE
ai-aimbot errors

### ISSUE THREAD

**Issue by prada-hvh** [SunOner/yolov8_aimbot#4]
Traceback (most recent call last):
  File "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "C:\Users\mofa\Source\Repos\wfai\main.py", line 1, in <module>
    from ultralytics import YOLO
  File "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\models\__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
    from .model import RTDETR
  File "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\models\rtdetr\model.py", line 10, in <module>
    from ultralytics.engine.model import Model
  File "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 8, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\cfg\__init__.py", line 10, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
  File "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\__init__.py", line 21, in <module>
    import torch
  File "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 193] %1 не является приложением Win32. Error loading "C:\Users\mofa\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\lib\cudnn_cnn_infer64_8.dll" or one of its dependencies.
Press any key to continue . . .

**Comment by prada-hvh** [comment]
certifi            2023.7.22
charset-normalizer 3.3.0
colorama           0.4.6
contourpy          1.1.1
cycler             0.12.1
filelock           3.12.4
fonttools          4.43.1
fsspec             2023.9.2
idna               3.4
install            1.3.5
Jinja2             3.1.2
kiwisolver         1.4.5
MarkupSafe         2.1.3
matplotlib         3.8.0
mpmath             1.3.0
networkx           3.2
numpy              1.26.1
opencv-python      4.8.1.78
packaging          23.2
pandas             2.1.1
Pillow             10.1.0
pip                23.3
psutil             5.9.6
py-cpuinfo         9.0.0
pyparsing          3.1.1
python-dateutil    2.8.2
pytz               2023.3.post1
pywin32            306
PyYAML             6.0.1
requests           2.31.0
scipy              1.11.3
seaborn            0.13.0
setuptools         65.5.0
six                1.16.0
sympy              1.12
tensorrt           8.6.1
tensorrt-dispatch  8.6.1
tensorrt-lean      8.6.1
thop               0.1.1.post2209072238
torch              2.1.0
torchvision        0.16.0
tqdm               4.66.1
typing_extensions  4.8.0
tzdata             2023.3
ultralytics        8.0.200
urllib3            2.0.7
