### ISSUE TITLE
error while exporting .pt model to .engine

### ISSUE THREAD

**Issue by cats-ui** [SunOner/yolov8_aimbot#40]
C:\Users\poo>yolo export model="models/sunxds_0.2.1_nano_320.pt" format=engine half=true device=0 workspace=8 imgsz=320 verbose=False
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\poo\AppData\Local\Programs\Python\Python311\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\poo\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\cfg\__init__.py", line 423, in entrypoint
    model = YOLO(model, task=task)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poo\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 94, in __init__
    self._load(model, task)
  File "C:\Users\poo\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 146, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poo\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 628, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poo\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\nn\tasks.py", line 567, in torch_safe_load
    return torch.load(file, map_location='cpu'), file  # load
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poo\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poo\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poo\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'models\\sunxds_0.2.1_nano_320.pt'

C:\Users\poo>cd C:\Users\poo\yolov8_aimbot-main

C:\Users\poo\yolov8_aimbot-main>C:\Users\poo\yolov8_aimbot-main
'C:\Users\poo\yolov8_aimbot-main' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\poo\yolov8_aimbot-main>yolo export model="models/sunxds_0.2.1_nano_320.pt" format=engine half=true device=0 workspace=8 imgsz=320 verbose=False
Ultralytics YOLOv8.0.221 🚀 Python-3.11.6 torch-2.1.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4070, 12282MiB)
Model summary (fused): 168 layers, 3007598 parameters, 0 gradients, 8.1 GFLOPs

PyTorch: starting from 'models\sunxds_0.2.1_nano_320.pt' with input shape (1, 3, 320, 320) BCHW and output shape(s) (1, 14, 2100) (5.9 MB)
TensorRT: export failure ❌ 0.1s: Could not find: cudnn64_8.dll. Is it on your PATH?
Note: Paths searched were:
['C:\\Users\\poo\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cv2\\../../x64/vc14/bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\libnvvp', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common', 'C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR', 'C:\\Program Files\\dotnet\\', 'C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2023.1.0\\', 'C:\\Users\\poo\\yolov8_aimbot-main\\TensorRT-8.6.1.6\\lib', 'C:\\Users\\poo\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\', 'C:\\Users\\poo\\AppData\\Local\\Programs\\Python\\Python311\\', 'C:\\Users\\poo\\AppData\\Local\\Programs\\Python\\Launcher\\', 'C:\\Users\\poo\\AppData\\Local\\Microsoft\\WindowsApps', '']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\poo\AppData\Local\Programs\Python\Python311\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\poo\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\cfg\__init__.py", line 448, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poo\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 310, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poo\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poo\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\exporter.py", line 252, in __call__
    f[1], _ = self.export_engine()
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poo\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\exporter.py", line 122, in outer_func
    raise e
  File "C:\Users\poo\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\exporter.py", line 117, in outer_func
    f, model = inner_func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poo\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\exporter.py", line 578, in export_engine
    import tensorrt as trt  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\poo\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorrt\__init__.py", line 127, in <module>
    ctypes.CDLL(find_lib(lib))
                ^^^^^^^^^^^^^
  File "C:\Users\poo\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorrt\__init__.py", line 81, in find_lib
    raise FileNotFoundError(
FileNotFoundError: Could not find: cudnn64_8.dll. Is it on your PATH?
Note: Paths searched were:
['C:\\Users\\poo\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cv2\\../../x64/vc14/bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\libnvvp', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common', 'C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR', 'C:\\Program Files\\dotnet\\', 'C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2023.1.0\\', 'C:\\Users\\poo\\yolov8_aimbot-main\\TensorRT-8.6.1.6\\lib', 'C:\\Users\\poo\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\', 'C:\\Users\\poo\\AppData\\Local\\Programs\\Python\\Python311\\', 'C:\\Users\\poo\\AppData\\Local\\Programs\\Python\\Launcher\\', 'C:\\Users\\poo\\AppData\\Local\\Microsoft\\WindowsApps', '']

**Comment by egorka2902** [comment]
всё равно не работает,даже после замены длл
