### ISSUE TITLE
Помогите)) 

### ISSUE THREAD

**Issue by Jolenkov123** [SunOner/yolov8_aimbot#46]
C:\Users\Windows 10\Desktop\yolov8_aimbot-main>python main.py
Model loaded. None
Aimbot is started. Enjoy!
[Right mouse button] - Aiming at the target
[F2] - EXIT
Ultralytics YOLOv8.0.222 🚀 Python-3.11.6 torch-2.1.1+cpu
Traceback (most recent call last):
  File "C:\Users\Windows 10\Desktop\yolov8_aimbot-main\main.py", line 160, in <module>
    init()
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows 10\Desktop\yolov8_aimbot-main\main.py", line 101, in init
    result = model.predict(
             ^^^^^^^^^^^^^^
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 232, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 318, in setup_model
    device=select_device(self.args.device, verbose=verbose),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Windows 10\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\torch_utils.py", line 119, in select_device
    raise ValueError(f"Invalid CUDA 'device={device}' requested."
ValueError: Invalid CUDA 'device=0' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: None
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.

**Comment by SunOner** [comment]
torch.cuda.is_available(): False
Переустанови torch с поддержкой cuda

**Comment by Konay23131** [comment]
ку можешь сылку кмнуть где можно скачать факел с поддержкой cuda.

**Comment by SunOner** [comment]
> ку можешь сылку кмнуть где можно скачать факел с поддержкой cuda.

Загугли, это не единичный случай.
