### ISSUE TITLE
работала и после обновления pytorch отъебнула

### ISSUE THREAD

**Issue by prada-hvh** [SunOner/yolov8_aimbot#47]
Model loaded. None
Ultralytics YOLOv8.0.222 🚀 Python-3.11.6 torch-2.1.0+cpu
Traceback (most recent call last):
  File "E:\yolik\main.py", line 145, in <module>
    init()
  File "C:\Users\plyas\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\yolik\main.py", line 86, in init
    result = model.predict(
             ^^^^^^^^^^^^^^
  File "C:\Users\plyas\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 232, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "C:\Users\plyas\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\predictor.py", line 318, in setup_model
    device=select_device(self.args.device, verbose=verbose),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\plyas\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\utils\torch_utils.py", line 119, in select_device
    raise ValueError(f"Invalid CUDA 'device={device}' requested."
ValueError: Invalid CUDA 'device=0' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: None
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.

**Comment by cats-ui** [comment]
pip uninstall torch
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

**Comment by prada-hvh** [comment]
> хуль у тя все падает постоянно, и зачем создавать новое issue если фикс уже лежит в старом

переставлял торч в этом и прикол

**Comment by cats-ui** [comment]
> > хуль у тя все падает постоянно, и зачем создавать новое issue если фикс уже лежит в старом
> 
> переставлял торч в этом и прикол

куда переставлял? зачем? почему?

**Comment by cats-ui** [comment]
закрывайте issue
