### ISSUE TITLE
python main.py,Error

### ISSUE THREAD

**Issue by ckx382** [SunOner/yolov8_aimbot#48]
PS D:\yolo\yolov8-xhx> python main.py
Traceback (most recent call last):
  File "D:\yolo\yolov8-xhx\main.py", line 2, in <module>
    from ultralytics import YOLO
  File "G:\Python\Lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "G:\Python\Lib\site-packages\ultralytics\models\__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "G:\Python\Lib\site-packages\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
    from .model import RTDETR
  File "G:\Python\Lib\site-packages\ultralytics\models\rtdetr\model.py", line 10, in <module>
    from ultralytics.engine.model import Model
  File "G:\Python\Lib\site-packages\ultralytics\engine\model.py", line 8, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File "G:\Python\Lib\site-packages\ultralytics\cfg\__init__.py", line 10, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
  File "G:\Python\Lib\site-packages\ultralytics\utils\__init__.py", line 19, in <module>
    import matplotlib.pyplot as plt
  File "G:\Python\Lib\site-packages\matplotlib\__init__.py", line 188, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "G:\Python\Lib\site-packages\matplotlib\cbook.py", line 32, in <module>
    from matplotlib import _api, _c_internal_utils
ImportError: cannot import name '_c_internal_utils' from partially initialized module 'matplotlib' (most likely due to a circular import) (G:\Python\Lib\site-packages\matplotlib\__init__.py)

**Comment by SunOner** [comment]
Try to reinstall Ultralytics

**Comment by cats-ui** [comment]
try to do this if reinstalling ultralytics is not working
   pip install --upgrade matplotlib
 pip install numpy==1.20.3

**Comment by cats-ui** [comment]
> Author
what

**Comment by cats-ui** [comment]
> @cats-ui Uninstall python completely, and install 3.11.6 to fix the problem

what?
