### ISSUE TITLE
RTX 4090 ? and issue  TensorRT: export failure ❌ 0.6s: Could not find: cudnn64_8.dll.

### ISSUE THREAD

**Issue by Shveps4032000** [SunOner/yolov8_aimbot#54]
`PyTorch: starting from 'models\sunxds_0.2.1_nano_320.pt' with input shape (1, 3, 320, 320) BCHW and output shape(s) (1, 14, 2100) (5.9 MB)
TensorRT: export failure ❌ 0.6s: Could not find: cudnn64_8.dll. Is it on your PATH?
Note: Paths searched were:
['C:\\Users\\vakut\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\cv2\\../../x64/vc14/bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.1\\libnvvp', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR', 'C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common', 'C:\\Program Files\\NVIDIA Corporation\\Nsight Compute 2023.1.0\\', 'C:\\Users\\vakut\\OneDrive\\Desktop\\yolov8_aimbot-main\\TensorRT-8.6.1.6\\TensorRT-8.6.1.6\\lib', 'C:\\Users\\vakut\\AppData\\Local\\Programs\\Python\\Python311\\Scripts\\', 'C:\\Users\\vakut\\AppData\\Local\\Programs\\Python\\Python311\\', 'C:\\Users\\vakut\\AppData\\Local\\Microsoft\\WindowsApps', '']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\vakut\AppData\Local\Programs\Python\Python311\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\vakut\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\cfg\__init__.py", line 448, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vakut\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 310, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vakut\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vakut\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\exporter.py", line 252, in __call__
    f[1], _ = self.export_engine()
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vakut\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\exporter.py", line 122, in outer_func
    raise e
  File "C:\Users\vakut\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\exporter.py", line 117, in outer_func
    f, model = inner_func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vakut\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\exporter.py", line 578, in export_engine
    import tensorrt as trt  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vakut\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorrt\__init__.py", line 127, in <module>
    ctypes.CDLL(find_lib(lib))
                ^^^^^^^^^^^^^
  File "C:\Users\vakut\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorrt\__init__.py", line 81, in find_lib
    raise FileNotFoundError(
FileNotFoundError: Could not find: cudnn64_8.dll. Is it on your PATH?`

Something wrong with a path could it be issue with the Graphics card ?

**Comment by cats-ui** [comment]
[cudnn64_8.zip](https://github.com/SunOner/yolov8_aimbot/files/13533178/cudnn64_8.zip)
Here's the fix
U need to place it here
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6/bin

**Comment by cats-ui** [comment]
U can close the issue now

**Comment by Shveps4032000** [comment]
i will try it. thank you

**Comment by Shveps4032000** [comment]
.
