### ISSUE TITLE
TypeError: 'NoneType' object does not support the context manager protocol

### ISSUE THREAD

**Issue by Klabqq** [SunOner/yolov8_aimbot#70]
C:\Users\User\Desktop\yolov8_aimbot-main>yolo export model="models/sunxds_0.2.1_nano_320.pt" format=engine half=true device=0 imgsz=320
Ultralytics YOLOv8.0.225 🚀 Python-3.11.6 torch-2.1.1+cu121 CUDA:0 (NVIDIA GeForce GTX 750 Ti, 4096MiB)
Model summary (fused): 168 layers, 3007598 parameters, 0 gradients, 8.1 GFLOPs

PyTorch: starting from 'models\sunxds_0.2.1_nano_320.pt' with input shape (1, 3, 320, 320) BCHW and output shape(s) (1, 14, 2100) (5.9 MB)
requirements: Ultralytics requirement ['onnx>=1.12.0'] not found, attempting AutoUpdate...
Collecting onnx>=1.12.0
  Downloading onnx-1.15.0-cp311-cp311-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: numpy in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from onnx>=1.12.0) (1.26.2)
Requirement already satisfied: protobuf>=3.20.2 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from onnx>=1.12.0) (4.25.1)
Downloading onnx-1.15.0-cp311-cp311-win_amd64.whl (14.3 MB)
   ---------------------------------------- 14.3/14.3 MB 11.9 MB/s eta 0:00:00
Installing collected packages: onnx
Successfully installed onnx-1.15.0

requirements: AutoUpdate success ✅ 10.4s, installed 1 package: ['onnx>=1.12.0']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect

ONNX: starting export with onnx 1.15.0 opset 17...
ONNX: simplifying with onnxsim 0.4.35...
ONNX: export success ✅ 12.0s, saved as 'models\sunxds_0.2.1_nano_320.onnx' (5.8 MB)

TensorRT: starting export with TensorRT 8.6.1...
[12/10/2023-03:51:22] [TRT] [I] [MemUsageChange] Init CUDA: CPU +1, GPU +0, now: CPU 10223, GPU 815 (MiB)
[12/10/2023-03:51:29] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +130, GPU +0, now: CPU 11295, GPU 815 (MiB)
[12/10/2023-03:51:29] [TRT] [I] ----------------------------------------------------------------
[12/10/2023-03:51:29] [TRT] [I] Input filename:   models\sunxds_0.2.1_nano_320.onnx
[12/10/2023-03:51:29] [TRT] [I] ONNX IR version:  0.0.8
[12/10/2023-03:51:29] [TRT] [I] Opset version:    17
[12/10/2023-03:51:29] [TRT] [I] Producer name:    pytorch
[12/10/2023-03:51:29] [TRT] [I] Producer version: 2.1.1
[12/10/2023-03:51:29] [TRT] [I] Domain:
[12/10/2023-03:51:29] [TRT] [I] Model version:    0
[12/10/2023-03:51:29] [TRT] [I] Doc string:
[12/10/2023-03:51:29] [TRT] [I] ----------------------------------------------------------------
[12/10/2023-03:51:29] [TRT] [W] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
TensorRT: input "images" with shape(1, 3, 320, 320) DataType.HALF
TensorRT: output "output0" with shape(1, 14, 2100) DataType.HALF
TensorRT: building FP16 engine as models\sunxds_0.2.1_nano_320.engine
[12/10/2023-03:51:29] [TRT] [I] BuilderFlag::kTF32 is set but hardware does not support TF32. Disabling TF32.
[12/10/2023-03:51:29] [TRT] [I] Graph optimization time: 0.0508836 seconds.
[12/10/2023-03:51:29] [TRT] [I] BuilderFlag::kTF32 is set but hardware does not support TF32. Disabling TF32.
[12/10/2023-03:51:29] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[12/10/2023-03:51:29] [TRT] [E] 10: Could not find any implementation for node /model.0/conv/Conv.
[12/10/2023-03:51:29] [TRT] [E] 10: [optimizer.cpp::nvinfer1::builder::cgraph::LeafCNode::computeCosts::3869] Error Code 10: Internal Error (Could not find any implementation for node /model.0/conv/Conv.)
TensorRT: export failure ❌ 19.1s: 'NoneType' object does not support the context manager protocol
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\cfg\__init__.py", line 448, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\model.py", line 310, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\exporter.py", line 252, in __call__
    f[1], _ = self.export_engine()
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\exporter.py", line 122, in outer_func
    raise e
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\exporter.py", line 117, in outer_func
    f, model = inner_func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\ultralytics\engine\exporter.py", line 631, in export_engine
    with builder.build_engine(network, config) as engine, open(f, 'wb') as t:
TypeError: 'NoneType' object does not support the context manager protocol

**Comment by cats-ui** [comment]
prob cuz of gtx 750 ti

**Comment by cats-ui** [comment]
Hey, try exporting with do_constant_folding=True
